/* 
 * My Title
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ProductApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ProductApiTests
    {
        private ProductApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ProductApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProductApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ProductApi
            //Assert.IsInstanceOfType(typeof(ProductApi), instance, "instance is a ProductApi");
        }

        
        /// <summary>
        /// Test ProductDeleteProduct
        /// </summary>
        [Test]
        public void ProductDeleteProductTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //var response = instance.ProductDeleteProduct(id);
            //Assert.IsInstanceOf<Products> (response, "response is Products");
        }
        
        /// <summary>
        /// Test ProductGetProduct
        /// </summary>
        [Test]
        public void ProductGetProductTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //var response = instance.ProductGetProduct(id);
            //Assert.IsInstanceOf<Products> (response, "response is Products");
        }
        
        /// <summary>
        /// Test ProductGetProducts
        /// </summary>
        [Test]
        public void ProductGetProductsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ProductGetProducts();
            //Assert.IsInstanceOf<List<Products>> (response, "response is List<Products>");
        }
        
        /// <summary>
        /// Test ProductPostProduct
        /// </summary>
        [Test]
        public void ProductPostProductTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Products product = null;
            //var response = instance.ProductPostProduct(product);
            //Assert.IsInstanceOf<Products> (response, "response is Products");
        }
        
        /// <summary>
        /// Test ProductPutProduct
        /// </summary>
        [Test]
        public void ProductPutProductTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //Products product = null;
            //var response = instance.ProductPutProduct(id, product);
            //Assert.IsInstanceOf<System.IO.Stream> (response, "response is System.IO.Stream");
        }
        
    }

}
